# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.316.2780
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ActionBeacon(BaseModel):
    """
    List of action beacons for the current page
    """ # noqa: E501
    beacon_type: StrictStr = Field(description="Type of beacon", alias="beaconType")
    bytes_ingested_metadata: Optional[StrictInt] = Field(default=None, description="Bytes ingested for metadata", alias="bytesIngestedMetadata")
    event_type: Optional[StrictStr] = Field(default=None, description="Event type (e.g., st=start, fs=frustration signal, oc=orientation change)", alias="eventType")
    frustration_signal: Optional[StrictStr] = Field(default=None, description="Frustration signal type (e.g., rt=rage tap)", alias="frustrationSignal")
    keyboard_operation: Optional[StrictStr] = Field(default=None, description="Keyboard operation indicator", alias="keyboardOperation")
    mobile_app_id: StrictStr = Field(description="Mobile app identifier", alias="mobileAppId")
    orientation_change: Optional[StrictStr] = Field(default=None, description="Orientation change indicator (l=landscape, p=portrait)", alias="orientationChange")
    scroll_direction: Optional[StrictStr] = Field(default=None, description="Scroll direction", alias="scrollDirection")
    scroll_duration: Optional[StrictStr] = Field(default=None, description="Scroll duration in milliseconds", alias="scrollDuration")
    session_id: StrictStr = Field(description="Session identifier", alias="sessionId")
    session_replay_version: Optional[StrictStr] = Field(default=None, description="Session replay version", alias="sessionReplayVersion")
    timestamp: StrictInt = Field(description="Timestamp when the action was captured (epoch milliseconds)")
    view_component_class_name: Optional[StrictStr] = Field(default=None, description="View component class name", alias="viewComponentClassName")
    view_component_id: Optional[StrictStr] = Field(default=None, description="View component identifier", alias="viewComponentId")
    __properties: ClassVar[List[str]] = ["beaconType", "bytesIngestedMetadata", "eventType", "frustrationSignal", "keyboardOperation", "mobileAppId", "orientationChange", "scrollDirection", "scrollDuration", "sessionId", "sessionReplayVersion", "timestamp", "viewComponentClassName", "viewComponentId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActionBeacon from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if bytes_ingested_metadata (nullable) is None
        # and model_fields_set contains the field
        if self.bytes_ingested_metadata is None and "bytes_ingested_metadata" in self.model_fields_set:
            _dict['bytesIngestedMetadata'] = None

        # set to None if event_type (nullable) is None
        # and model_fields_set contains the field
        if self.event_type is None and "event_type" in self.model_fields_set:
            _dict['eventType'] = None

        # set to None if frustration_signal (nullable) is None
        # and model_fields_set contains the field
        if self.frustration_signal is None and "frustration_signal" in self.model_fields_set:
            _dict['frustrationSignal'] = None

        # set to None if keyboard_operation (nullable) is None
        # and model_fields_set contains the field
        if self.keyboard_operation is None and "keyboard_operation" in self.model_fields_set:
            _dict['keyboardOperation'] = None

        # set to None if orientation_change (nullable) is None
        # and model_fields_set contains the field
        if self.orientation_change is None and "orientation_change" in self.model_fields_set:
            _dict['orientationChange'] = None

        # set to None if scroll_direction (nullable) is None
        # and model_fields_set contains the field
        if self.scroll_direction is None and "scroll_direction" in self.model_fields_set:
            _dict['scrollDirection'] = None

        # set to None if scroll_duration (nullable) is None
        # and model_fields_set contains the field
        if self.scroll_duration is None and "scroll_duration" in self.model_fields_set:
            _dict['scrollDuration'] = None

        # set to None if session_replay_version (nullable) is None
        # and model_fields_set contains the field
        if self.session_replay_version is None and "session_replay_version" in self.model_fields_set:
            _dict['sessionReplayVersion'] = None

        # set to None if view_component_class_name (nullable) is None
        # and model_fields_set contains the field
        if self.view_component_class_name is None and "view_component_class_name" in self.model_fields_set:
            _dict['viewComponentClassName'] = None

        # set to None if view_component_id (nullable) is None
        # and model_fields_set contains the field
        if self.view_component_id is None and "view_component_id" in self.model_fields_set:
            _dict['viewComponentId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActionBeacon from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "beaconType": obj.get("beaconType"),
            "bytesIngestedMetadata": obj.get("bytesIngestedMetadata"),
            "eventType": obj.get("eventType"),
            "frustrationSignal": obj.get("frustrationSignal"),
            "keyboardOperation": obj.get("keyboardOperation"),
            "mobileAppId": obj.get("mobileAppId"),
            "orientationChange": obj.get("orientationChange"),
            "scrollDirection": obj.get("scrollDirection"),
            "scrollDuration": obj.get("scrollDuration"),
            "sessionId": obj.get("sessionId"),
            "sessionReplayVersion": obj.get("sessionReplayVersion"),
            "timestamp": obj.get("timestamp"),
            "viewComponentClassName": obj.get("viewComponentClassName"),
            "viewComponentId": obj.get("viewComponentId")
        })
        return _obj


