# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from instana_client.models.advanced_filter import AdvancedFilter
from instana_client.models.service_level_indicator import ServiceLevelIndicator
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AdvancedCustomBlueprintIndicator(ServiceLevelIndicator):
    """
    AdvancedCustomBlueprintIndicator
    """ # noqa: E501
    bad_events: Optional[AdvancedFilter] = Field(default=None, alias="badEvents")
    good_events: AdvancedFilter = Field(alias="goodEvents")
    __properties: ClassVar[List[str]] = ["aggregation", "blueprint", "operator", "serviceLevelsMeasurement", "threshold", "type", "badEvents", "goodEvents"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdvancedCustomBlueprintIndicator from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of bad_events
        if self.bad_events:
            _dict['badEvents'] = self.bad_events.to_dict()
        # override the default output from pydantic by calling `to_dict()` of good_events
        if self.good_events:
            _dict['goodEvents'] = self.good_events.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdvancedCustomBlueprintIndicator from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aggregation": obj.get("aggregation"),
            "blueprint": obj.get("blueprint"),
            "operator": obj.get("operator"),
            "serviceLevelsMeasurement": obj.get("serviceLevelsMeasurement"),
            "threshold": obj.get("threshold"),
            "type": obj.get("type"),
            "badEvents": AdvancedFilter.from_dict(obj["badEvents"]) if obj.get("badEvents") is not None else None,
            "goodEvents": AdvancedFilter.from_dict(obj["goodEvents"]) if obj.get("goodEvents") is not None else None
        })
        return _obj


