# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from instana_client.models.slo_entity import SloEntity
from instana_client.models.tag_filter_expression_element import TagFilterExpressionElement
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ApplicationSloEntity(SloEntity):
    """
    ApplicationSloEntity
    """ # noqa: E501
    application_id: Annotated[str, Field(min_length=1, strict=True)] = Field(description="The ID of the Application", alias="applicationId")
    boundary_scope: StrictStr = Field(description="The Boundary Scope of the Application", alias="boundaryScope")
    endpoint_id: Optional[StrictStr] = Field(default=None, description="The Endpoint ID of the Application", alias="endpointId")
    include_internal: StrictBool = Field(description="A boolean value indicating whether the SLO takes Internal calls into account", alias="includeInternal")
    include_synthetic: StrictBool = Field(description="A boolean value indicating whether the SLO takes Synthetic calls into account", alias="includeSynthetic")
    service_id: Optional[StrictStr] = Field(default=None, description="The Service ID of the Application", alias="serviceId")
    __properties: ClassVar[List[str]] = ["tagFilterExpression", "type", "applicationId", "boundaryScope", "endpointId", "includeInternal", "includeSynthetic", "serviceId"]

    @field_validator('boundary_scope')
    def boundary_scope_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ALL', 'INBOUND']):
            raise ValueError("must be one of enum values ('ALL', 'INBOUND')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApplicationSloEntity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tag_filter_expression
        if self.tag_filter_expression:
            _dict['tagFilterExpression'] = self.tag_filter_expression.to_dict()
        # set to None if tag_filter_expression (nullable) is None
        # and model_fields_set contains the field
        if self.tag_filter_expression is None and "tag_filter_expression" in self.model_fields_set:
            _dict['tagFilterExpression'] = None

        # set to None if endpoint_id (nullable) is None
        # and model_fields_set contains the field
        if self.endpoint_id is None and "endpoint_id" in self.model_fields_set:
            _dict['endpointId'] = None

        # set to None if service_id (nullable) is None
        # and model_fields_set contains the field
        if self.service_id is None and "service_id" in self.model_fields_set:
            _dict['serviceId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApplicationSloEntity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tagFilterExpression": TagFilterExpressionElement.from_dict(obj["tagFilterExpression"]) if obj.get("tagFilterExpression") is not None else None,
            "type": obj.get("type"),
            "applicationId": obj.get("applicationId"),
            "boundaryScope": obj.get("boundaryScope"),
            "endpointId": obj.get("endpointId"),
            "includeInternal": obj.get("includeInternal"),
            "includeSynthetic": obj.get("includeSynthetic"),
            "serviceId": obj.get("serviceId")
        })
        return _obj


