# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.324.1358
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Evaluator(BaseModel):
    """
    Evaluator
    """ # noqa: E501
    criteria: StrictStr
    evaluator_id: Optional[StrictStr] = Field(default=None, alias="evaluatorId")
    evaluator_name: StrictStr = Field(alias="evaluatorName")
    is_built_in: Optional[StrictBool] = Field(default=None, alias="isBuiltIn")
    mean_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="meanScore")
    number_of_runs: Optional[StrictInt] = Field(default=None, alias="numberOfRuns")
    pass_rate_mean: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="passRateMean")
    threshold: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["criteria", "evaluatorId", "evaluatorName", "isBuiltIn", "meanScore", "numberOfRuns", "passRateMean", "threshold"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Evaluator from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Evaluator from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "criteria": obj.get("criteria"),
            "evaluatorId": obj.get("evaluatorId"),
            "evaluatorName": obj.get("evaluatorName"),
            "isBuiltIn": obj.get("isBuiltIn"),
            "meanScore": obj.get("meanScore"),
            "numberOfRuns": obj.get("numberOfRuns"),
            "passRateMean": obj.get("passRateMean"),
            "threshold": obj.get("threshold")
        })
        return _obj


