# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from instana_client.models.entity_health_info import EntityHealthInfo
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InfrastructureItem(BaseModel):
    """
    InfrastructureItem
    """ # noqa: E501
    adjusted_granularities: Optional[Dict[str, StrictInt]] = Field(default=None, description="map of metric keys to their adjusted granularity (in milliseconds)", alias="adjustedGranularities")
    entity_health_info: Optional[EntityHealthInfo] = Field(default=None, alias="entityHealthInfo")
    label: Optional[StrictStr] = None
    metrics: Optional[Dict[str, List[List[Union[StrictFloat, StrictInt]]]]] = None
    plugin: Optional[StrictStr] = None
    snapshot_id: Optional[StrictStr] = Field(default=None, alias="snapshotId")
    tags: Optional[Dict[str, StrictStr]] = None
    time: Optional[StrictInt] = Field(default=None, description="Epoch time in milliseconds if the snapshot is offline. Set to 9223372036854775807 if the snapshot is online.")
    __properties: ClassVar[List[str]] = ["adjustedGranularities", "entityHealthInfo", "label", "metrics", "plugin", "snapshotId", "tags", "time"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InfrastructureItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of entity_health_info
        if self.entity_health_info:
            _dict['entityHealthInfo'] = self.entity_health_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InfrastructureItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "adjustedGranularities": obj.get("adjustedGranularities"),
            "entityHealthInfo": EntityHealthInfo.from_dict(obj["entityHealthInfo"]) if obj.get("entityHealthInfo") is not None else None,
            "label": obj.get("label"),
            "metrics": obj.get("metrics"),
            "plugin": obj.get("plugin"),
            "snapshotId": obj.get("snapshotId"),
            "tags": obj.get("tags"),
            "time": obj.get("time")
        })
        return _obj


