# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from instana_client.models.sampling_metadata import SamplingMetadata
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InfrastructureGroup(BaseModel):
    """
    group of infrastructure entities
    """ # noqa: E501
    adjusted_granularities: Optional[Dict[str, StrictInt]] = Field(default=None, description="map of metric keys to their adjusted granularity (in milliseconds)", alias="adjustedGranularities")
    count: Optional[StrictInt] = Field(default=None, description="number of entities in this group")
    metrics: Optional[Dict[str, List[List[Union[StrictFloat, StrictInt]]]]] = Field(default=None, description="map of metric keys to array of timestamp,value pairs")
    poll_rate: Optional[StrictInt] = Field(default=None, description="max poll rate across this group", alias="pollRate")
    sampling_metadata: Optional[SamplingMetadata] = Field(default=None, alias="samplingMetadata")
    tags: Optional[Dict[str, Dict[str, Any]]] = Field(default=None, description="tag keys and values for this group")
    __properties: ClassVar[List[str]] = ["adjustedGranularities", "count", "metrics", "pollRate", "samplingMetadata", "tags"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InfrastructureGroup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sampling_metadata
        if self.sampling_metadata:
            _dict['samplingMetadata'] = self.sampling_metadata.to_dict()
        # set to None if sampling_metadata (nullable) is None
        # and model_fields_set contains the field
        if self.sampling_metadata is None and "sampling_metadata" in self.model_fields_set:
            _dict['samplingMetadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InfrastructureGroup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "adjustedGranularities": obj.get("adjustedGranularities"),
            "count": obj.get("count"),
            "metrics": obj.get("metrics"),
            "pollRate": obj.get("pollRate"),
            "samplingMetadata": SamplingMetadata.from_dict(obj["samplingMetadata"]) if obj.get("samplingMetadata") is not None else None,
            "tags": obj.get("tags")
        })
        return _obj


