# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from instana_client.models.ip_filtering_rule_dto import IPFilteringRuleDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IPFiltering(BaseModel):
    """
    IPFiltering
    """ # noqa: E501
    active: Optional[StrictBool] = Field(default=None, description="If the configuration is currently enforced, can be permanent active (if verified), or temporary after creation (enabling the verification).")
    deny_all: Optional[StrictBool] = Field(default=None, description="Fallback configuration, if unmatched requests should be denied.", alias="denyAll")
    enabled: Optional[StrictBool] = Field(default=None, description="If the configuration should be enforced. See active status if it is actually enforced.")
    last_changed_at: Optional[StrictInt] = Field(default=None, description="When the configuration was last changed.", alias="lastChangedAt")
    last_verified_at: Optional[StrictInt] = Field(default=None, description="When the configuration was last verified. Can be used to assume if a configuration needs to be verified.", alias="lastVerifiedAt")
    rules: List[IPFilteringRuleDto] = Field(description="Actual traffic rules. Enforcing allow / block based on incoming IP address. Are evaluated in given order.")
    support_access_enabled: Optional[StrictBool] = Field(default=None, description="If Instana support should be able to access your environment. Instana support is still able to to deactivate the configuration for you (manual process).", alias="supportAccessEnabled")
    __properties: ClassVar[List[str]] = ["active", "denyAll", "enabled", "lastChangedAt", "lastVerifiedAt", "rules", "supportAccessEnabled"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IPFiltering from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rules (list)
        _items = []
        if self.rules:
            for _item_rules in self.rules:
                if _item_rules:
                    _items.append(_item_rules.to_dict())
            _dict['rules'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IPFiltering from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "denyAll": obj.get("denyAll"),
            "enabled": obj.get("enabled"),
            "lastChangedAt": obj.get("lastChangedAt"),
            "lastVerifiedAt": obj.get("lastVerifiedAt"),
            "rules": [IPFilteringRuleDto.from_dict(_item) for _item in obj["rules"]] if obj.get("rules") is not None else None,
            "supportAccessEnabled": obj.get("supportAccessEnabled")
        })
        return _obj


