# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.324.1358
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from instana_client.models.ip_filtering_rule_dto import IPFilteringRuleDto
from typing import Optional, Set
from typing_extensions import Self

class IPFilteringUpsert(BaseModel):
    """
    IPFilteringUpsert
    """ # noqa: E501
    deny_all: StrictBool = Field(description="Fallback configuration, if unmatched requests should be denied.", alias="denyAll")
    enabled: StrictBool = Field(description="If the configuration should be enforced. See active status if it is actually enforced.")
    rules: Annotated[List[IPFilteringRuleDto], Field(min_length=1, max_length=75)] = Field(description="Actual traffic rules. Enforcing allow / block based on incoming IP address. Are evaluated in given order.")
    support_access_enabled: Optional[StrictBool] = Field(default=None, description="Optional flag for future support access functionality. Currently has no effect and defaults to false if not provided. Instana support is still able to deactivate the configuration for you (manual process).", alias="supportAccessEnabled")
    __properties: ClassVar[List[str]] = ["denyAll", "enabled", "rules", "supportAccessEnabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IPFilteringUpsert from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rules (list)
        _items = []
        if self.rules:
            for _item_rules in self.rules:
                if _item_rules:
                    _items.append(_item_rules.to_dict())
            _dict['rules'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IPFilteringUpsert from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "denyAll": obj.get("denyAll"),
            "enabled": obj.get("enabled"),
            "rules": [IPFilteringRuleDto.from_dict(_item) for _item in obj["rules"]] if obj.get("rules") is not None else None,
            "supportAccessEnabled": obj.get("supportAccessEnabled")
        })
        return _obj


