# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.315.1425
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from instana_client.models.llm_gateway_capability import LLMGatewayCapability
from instana_client.models.llm_gateway_model import LLMGatewayModel
from instana_client.models.llm_gateway_service import LLMGatewayService
from typing import Optional, Set
from typing_extensions import Self

class LLMEgressGateway(BaseModel):
    """
    Custom handler definition.
    """ # noqa: E501
    capabilities: List[LLMGatewayCapability]
    created_at: Optional[StrictStr] = Field(default=None, alias="createdAt")
    description: Optional[StrictStr] = None
    enabled: Optional[StrictBool] = None
    id: UUID
    instana_agents: Optional[Dict[str, Any]] = Field(default=None, alias="instanaAgents")
    metadata: Optional[Dict[str, Any]] = None
    model: LLMGatewayModel
    modified_at: Optional[StrictStr] = Field(default=None, alias="modifiedAt")
    name: Annotated[str, Field(min_length=1, strict=True)]
    prompt: Optional[StrictStr] = None
    service: LLMGatewayService
    system: Optional[StrictBool] = None
    tenant_unit_id: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="tenantUnitId")
    __properties: ClassVar[List[str]] = ["capabilities", "createdAt", "description", "enabled", "id", "instanaAgents", "metadata", "model", "modifiedAt", "name", "prompt", "service", "system", "tenantUnitId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LLMEgressGateway from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in capabilities (list)
        _items = []
        if self.capabilities:
            for _item_capabilities in self.capabilities:
                if _item_capabilities:
                    _items.append(_item_capabilities.to_dict())
            _dict['capabilities'] = _items
        # override the default output from pydantic by calling `to_dict()` of model
        if self.model:
            _dict['model'] = self.model.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service
        if self.service:
            _dict['service'] = self.service.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LLMEgressGateway from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "capabilities": [LLMGatewayCapability.from_dict(_item) for _item in obj["capabilities"]] if obj.get("capabilities") is not None else None,
            "createdAt": obj.get("createdAt"),
            "description": obj.get("description"),
            "enabled": obj.get("enabled"),
            "id": obj.get("id"),
            "instanaAgents": obj.get("instanaAgents"),
            "metadata": obj.get("metadata"),
            "model": LLMGatewayModel.from_dict(obj["model"]) if obj.get("model") is not None else None,
            "modifiedAt": obj.get("modifiedAt"),
            "name": obj.get("name"),
            "prompt": obj.get("prompt"),
            "service": LLMGatewayService.from_dict(obj["service"]) if obj.get("service") is not None else None,
            "system": obj.get("system"),
            "tenantUnitId": obj.get("tenantUnitId")
        })
        return _obj


