# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.320.1414
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from instana_client.models.custom_payload_field import CustomPayloadField
from instana_client.models.metric_field_value import MetricFieldValue
from typing import Optional, Set
from typing_extensions import Self

class MetricField(CustomPayloadField):
    """
    MetricField
    """ # noqa: E501
    aggregation: Optional[StrictStr] = None
    entity_type: Optional[StrictStr] = Field(default=None, alias="entityType")
    metric_id: Optional[StrictStr] = Field(default=None, alias="metricId")
    source: Optional[StrictStr] = None
    time_window: Optional[Dict[str, Any]] = Field(default=None, alias="timeWindow")
    value: Optional[MetricFieldValue] = None
    __properties: ClassVar[List[str]] = ["key", "type", "aggregation", "entityType", "metricId", "source", "timeWindow", "value"]

    @field_validator('aggregation')
    def aggregation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SUM', 'MEAN', 'MIN', 'MAX']):
            raise ValueError("must be one of enum values ('SUM', 'MEAN', 'MIN', 'MAX')")
        return value

    @field_validator('source')
    def source_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['INFRA', 'APPLICATION']):
            raise ValueError("must be one of enum values ('INFRA', 'APPLICATION')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MetricField from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of value
        if self.value:
            _dict['value'] = self.value.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MetricField from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "key": obj.get("key"),
            "type": obj.get("type"),
            "aggregation": obj.get("aggregation"),
            "entityType": obj.get("entityType"),
            "metricId": obj.get("metricId"),
            "source": obj.get("source"),
            "timeWindow": obj.get("timeWindow"),
            "value": MetricFieldValue.from_dict(obj["value"]) if obj.get("value") is not None else None
        })
        return _obj


