# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RuleInput(BaseModel):
    """
    List of input rules of the Built-in Event Specification
    """ # noqa: E501
    input_kind: StrictStr = Field(alias="inputKind")
    input_name: Annotated[str, Field(min_length=0, strict=True, max_length=256)] = Field(alias="inputName")
    metric_rollup: Optional[StrictInt] = Field(default=None, alias="metricRollup")
    __properties: ClassVar[List[str]] = ["inputKind", "inputName", "metricRollup"]

    @field_validator('input_kind')
    def input_kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['METRIC', 'SNAPSHOT_FIELD', 'EVENT', 'DERIVED_METRIC', 'METRIC_PATTERN']):
            raise ValueError("must be one of enum values ('METRIC', 'SNAPSHOT_FIELD', 'EVENT', 'DERIVED_METRIC', 'METRIC_PATTERN')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RuleInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if metric_rollup (nullable) is None
        # and model_fields_set contains the field
        if self.metric_rollup is None and "metric_rollup" in self.model_fields_set:
            _dict['metricRollup'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RuleInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "inputKind": obj.get("inputKind"),
            "inputName": obj.get("inputName"),
            "metricRollup": obj.get("metricRollup")
        })
        return _obj


