# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SamplingMetadata(BaseModel):
    """
    Metadata about sampling applied to infrastructure metrics query
    """ # noqa: E501
    groups_sampled: Optional[StrictInt] = Field(default=None, description="Number of unique groups that were sampled", alias="groupsSampled")
    groups_skipped: Optional[StrictInt] = Field(default=None, description="Number of unique groups that were not sampled", alias="groupsSkipped")
    sampling_applied: Optional[StrictBool] = Field(default=None, description="Whether sampling was actually applied (true if any groups were sampled)", alias="samplingApplied")
    total_members_after: Optional[StrictInt] = Field(default=None, description="Total number of entity members after sampling", alias="totalMembersAfter")
    total_members_before: Optional[StrictInt] = Field(default=None, description="Total number of entity members before sampling", alias="totalMembersBefore")
    __properties: ClassVar[List[str]] = ["groupsSampled", "groupsSkipped", "samplingApplied", "totalMembersAfter", "totalMembersBefore"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SamplingMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if total_members_before (nullable) is None
        # and model_fields_set contains the field
        if self.total_members_before is None and "total_members_before" in self.model_fields_set:
            _dict['totalMembersBefore'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SamplingMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "groupsSampled": obj.get("groupsSampled"),
            "groupsSkipped": obj.get("groupsSkipped"),
            "samplingApplied": obj.get("samplingApplied"),
            "totalMembersAfter": obj.get("totalMembersAfter"),
            "totalMembersBefore": obj.get("totalMembersBefore")
        })
        return _obj


