# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.324.1358
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from instana_client.models.custom_payload_field import CustomPayloadField
from instana_client.models.synthetic_alert_rule import SyntheticAlertRule
from instana_client.models.synthetic_time_threshold import SyntheticTimeThreshold
from instana_client.models.tag_filter_expression_element import TagFilterExpressionElement
from typing import Optional, Set
from typing_extensions import Self

class SyntheticAlertConfigWithMetadata(BaseModel):
    """
    SyntheticAlertConfigWithMetadata
    """ # noqa: E501
    affected_locations_count: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of locations encounters failure", alias="affectedLocationsCount")
    alert_channel_ids: Annotated[List[Annotated[str, Field(min_length=1, strict=True)]], Field(min_length=0, max_length=1024)] = Field(description="List of IDs of alert channels defined in Instana. Can be left empty.", alias="alertChannelIds")
    created: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Unix timestamp representing the creation time of this revision.")
    custom_payload_fields: Annotated[List[CustomPayloadField], Field(min_length=0, max_length=20)] = Field(description="Custom payload fields to send additional information in the alert notifications. Can be left empty.", alias="customPayloadFields")
    description: Annotated[str, Field(min_length=0, strict=True, max_length=65536)] = Field(description="Description of the synthetic alert configuration. Used as a template for the description of alert/event notifications triggered by this Smart Alert configuration.")
    enabled: Optional[StrictBool] = Field(default=None, description="Flag to indicate whether or not the configuration is enabled.")
    evaluation_type: Optional[StrictStr] = Field(default=None, description="Determines whether synthetic test results are evaluated per location independently or grouped across all locations.", alias="evaluationType")
    grace_period: Optional[StrictInt] = Field(default=None, description="The duration for which an alert remains open after conditions are no longer violated, with the alert auto-closing once the grace period expires.", alias="gracePeriod")
    id: Annotated[str, Field(min_length=0, strict=True, max_length=64)] = Field(description="ID of this Synthetic Alert Config. ")
    include_on_demand: Optional[StrictBool] = Field(default=None, description="Controls whether on-demand synthetic test runs should be included in alert evaluation. When true, both scheduled and on-demand test runs are evaluated. When false, only scheduled test runs are evaluated. Default behavior when not provided: (1) If tagFilterExpression contains RUN_TYPE filter that is NOT 'Scheduled' → defaults to true; (2) If tagFilterExpression contains RUN_TYPE EQUALS 'Scheduled' → defaults to false; (3) If no RUN_TYPE filter exists → defaults to false.", alias="includeOnDemand")
    initial_created: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Unix timestamp representing the time of the initial revision.", alias="initialCreated")
    name: Annotated[str, Field(min_length=0, strict=True, max_length=256)] = Field(description="Name of the synthetic alert configuration. Used as a template for the title of alert/event notifications triggered by this Smart Alert configuration.")
    read_only: Optional[StrictBool] = Field(default=None, description="Flag to indicate whether or not the configuration is read-only. Read-only access restricts modification of the config.", alias="readOnly")
    rule: SyntheticAlertRule
    severity: Optional[Annotated[int, Field(le=10, strict=True, ge=5)]] = Field(default=None, description="The severity of the alert when triggered, which is either 5 (Warning), or 10 (Critical).")
    synthetic_test_ids: List[StrictStr] = Field(description="IDs of the synthetic tests that this Smart Alert configuration is applied to.", alias="syntheticTestIds")
    tag_filter_expression: Optional[TagFilterExpressionElement] = Field(alias="tagFilterExpression")
    time_threshold: SyntheticTimeThreshold = Field(alias="timeThreshold")
    __properties: ClassVar[List[str]] = ["affectedLocationsCount", "alertChannelIds", "created", "customPayloadFields", "description", "enabled", "evaluationType", "gracePeriod", "id", "includeOnDemand", "initialCreated", "name", "readOnly", "rule", "severity", "syntheticTestIds", "tagFilterExpression", "timeThreshold"]

    @field_validator('evaluation_type')
    def evaluation_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['PER_LOCATION', 'PER_SYNTHETIC_TEST']):
            raise ValueError("must be one of enum values ('PER_LOCATION', 'PER_SYNTHETIC_TEST')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SyntheticAlertConfigWithMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in custom_payload_fields (list)
        _items = []
        if self.custom_payload_fields:
            for _item_custom_payload_fields in self.custom_payload_fields:
                if _item_custom_payload_fields:
                    _items.append(_item_custom_payload_fields.to_dict())
            _dict['customPayloadFields'] = _items
        # override the default output from pydantic by calling `to_dict()` of rule
        if self.rule:
            _dict['rule'] = self.rule.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tag_filter_expression
        if self.tag_filter_expression:
            _dict['tagFilterExpression'] = self.tag_filter_expression.to_dict()
        # override the default output from pydantic by calling `to_dict()` of time_threshold
        if self.time_threshold:
            _dict['timeThreshold'] = self.time_threshold.to_dict()
        # set to None if affected_locations_count (nullable) is None
        # and model_fields_set contains the field
        if self.affected_locations_count is None and "affected_locations_count" in self.model_fields_set:
            _dict['affectedLocationsCount'] = None

        # set to None if evaluation_type (nullable) is None
        # and model_fields_set contains the field
        if self.evaluation_type is None and "evaluation_type" in self.model_fields_set:
            _dict['evaluationType'] = None

        # set to None if grace_period (nullable) is None
        # and model_fields_set contains the field
        if self.grace_period is None and "grace_period" in self.model_fields_set:
            _dict['gracePeriod'] = None

        # set to None if include_on_demand (nullable) is None
        # and model_fields_set contains the field
        if self.include_on_demand is None and "include_on_demand" in self.model_fields_set:
            _dict['includeOnDemand'] = None

        # set to None if tag_filter_expression (nullable) is None
        # and model_fields_set contains the field
        if self.tag_filter_expression is None and "tag_filter_expression" in self.model_fields_set:
            _dict['tagFilterExpression'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SyntheticAlertConfigWithMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "affectedLocationsCount": obj.get("affectedLocationsCount"),
            "alertChannelIds": obj.get("alertChannelIds"),
            "created": obj.get("created"),
            "customPayloadFields": [CustomPayloadField.from_dict(_item) for _item in obj["customPayloadFields"]] if obj.get("customPayloadFields") is not None else None,
            "description": obj.get("description"),
            "enabled": obj.get("enabled"),
            "evaluationType": obj.get("evaluationType"),
            "gracePeriod": obj.get("gracePeriod"),
            "id": obj.get("id"),
            "includeOnDemand": obj.get("includeOnDemand"),
            "initialCreated": obj.get("initialCreated"),
            "name": obj.get("name"),
            "readOnly": obj.get("readOnly"),
            "rule": SyntheticAlertRule.from_dict(obj["rule"]) if obj.get("rule") is not None else None,
            "severity": obj.get("severity"),
            "syntheticTestIds": obj.get("syntheticTestIds"),
            "tagFilterExpression": TagFilterExpressionElement.from_dict(obj["tagFilterExpression"]) if obj.get("tagFilterExpression") is not None else None,
            "timeThreshold": SyntheticTimeThreshold.from_dict(obj["timeThreshold"]) if obj.get("timeThreshold") is not None else None
        })
        return _obj


