# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TraceSamplingConfig(BaseModel):
    """
    TraceSamplingConfig
    """ # noqa: E501
    created_at: Optional[StrictInt] = Field(default=None, alias="createdAt")
    enabled: StrictBool
    evaluation_window_minutes: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, alias="evaluationWindowMinutes")
    retention_percentage: Optional[Union[Annotated[float, Field(le=100, strict=True, ge=0.01)], Annotated[int, Field(le=100, strict=True, ge=1)]]] = Field(default=None, alias="retentionPercentage")
    sampling_frequency_hours: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="samplingFrequencyHours")
    sampling_rate: Optional[Union[Annotated[float, Field(le=100, strict=True, ge=0)], Annotated[int, Field(le=100, strict=True, ge=0)]]] = Field(default=None, alias="samplingRate")
    sampling_type: StrictStr = Field(alias="samplingType")
    tenant_unit_id: Optional[StrictStr] = Field(default=None, alias="tenantUnitId")
    updated_at: Optional[StrictInt] = Field(default=None, alias="updatedAt")
    volume_strategy: StrictStr = Field(alias="volumeStrategy")
    __properties: ClassVar[List[str]] = ["createdAt", "enabled", "evaluationWindowMinutes", "retentionPercentage", "samplingFrequencyHours", "samplingRate", "samplingType", "tenantUnitId", "updatedAt", "volumeStrategy"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TraceSamplingConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TraceSamplingConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "enabled": obj.get("enabled"),
            "evaluationWindowMinutes": obj.get("evaluationWindowMinutes"),
            "retentionPercentage": obj.get("retentionPercentage"),
            "samplingFrequencyHours": obj.get("samplingFrequencyHours"),
            "samplingRate": obj.get("samplingRate"),
            "samplingType": obj.get("samplingType"),
            "tenantUnitId": obj.get("tenantUnitId"),
            "updatedAt": obj.get("updatedAt"),
            "volumeStrategy": obj.get("volumeStrategy")
        })
        return _obj


