# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from instana_client.models.abstract_integration import AbstractIntegration
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ZChatOpsIntegration(AbstractIntegration):
    """
    ZChatOpsIntegration
    """ # noqa: E501
    bearer_auth_token: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="bearerAuthToken")
    channels: Optional[Annotated[List[Annotated[str, Field(min_length=1, strict=True)]], Field(min_length=0, max_length=1)]] = None
    zchat_ops_incidents_url: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="zchatOpsIncidentsUrl")
    __properties: ClassVar[List[str]] = ["id", "kind", "name", "timezone", "bearerAuthToken", "channels", "zchatOpsIncidentsUrl"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ZChatOpsIntegration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if channels (nullable) is None
        # and model_fields_set contains the field
        if self.channels is None and "channels" in self.model_fields_set:
            _dict['channels'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ZChatOpsIntegration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "kind": obj.get("kind"),
            "name": obj.get("name"),
            "timezone": obj.get("timezone"),
            "bearerAuthToken": obj.get("bearerAuthToken"),
            "channels": obj.get("channels"),
            "zchatOpsIncidentsUrl": obj.get("zchatOpsIncidentsUrl")
        })
        return _obj


