# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.315.1425
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_internal_custom_dashboards(self) -> None:
        """Test case for get_internal_custom_dashboards

        """
        pass

    def test_get_internal_dashboard(self) -> None:
        """Test case for get_internal_dashboard

        """
        pass


if __name__ == '__main__':
    unittest.main()
