# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.api_log_item import ApiLogItem

class TestApiLogItem(unittest.TestCase):
    """ApiLogItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiLogItem:
        """Test ApiLogItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiLogItem`
        """
        model = ApiLogItem()
        if include_optional:
            return ApiLogItem(
                aws_ecs_container_id = '',
                aws_ecs_container_name = '',
                containerd_container_id = '',
                crio_container_id = '',
                docker_container_id = '',
                docker_container_name = '',
                garden_container_id = '',
                kubernetes_cluster_name = '',
                kubernetes_container_name = '',
                kubernetes_deployment_name = '',
                kubernetes_namespace_name = '',
                kubernetes_node_name = '',
                kubernetes_pod_name = '',
                log_applications = [
                    ''
                    ],
                log_custom = [
                    instana_client.models.api_log_tag.ApiLogTag(
                        key = '', 
                        name = '', 
                        value = instana_client.models.value.value(), )
                    ],
                log_exception_message = '',
                log_exception_stack_trace = '',
                log_exception_type = '',
                log_expiration_ts_seconds = '',
                log_file_path = '',
                log_host_id = '',
                log_host_name = '',
                log_level = '',
                log_message = '',
                log_process_id = '',
                log_service_id = '',
                log_service_name = '',
                log_stream_name = '',
                log_timestamp = 0,
                log_trace_id = ''
            )
        else:
            return ApiLogItem(
        )
        """

    def testApiLogItem(self):
        """Test ApiLogItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
