# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.customer_email import CustomerEmail

class TestCustomerEmail(unittest.TestCase):
    """CustomerEmail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerEmail:
        """Test CustomerEmail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerEmail`
        """
        model = CustomerEmail()
        if include_optional:
            return CustomerEmail(
                customer_email = '',
                email = ''
            )
        else:
            return CustomerEmail(
        )
        """

    def testCustomerEmail(self):
        """Test CustomerEmail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
