# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.advanced_filter import AdvancedFilter

class TestAdvancedFilter(unittest.TestCase):
    """AdvancedFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvancedFilter:
        """Test AdvancedFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvancedFilter`
        """
        model = AdvancedFilter()
        if include_optional:
            return AdvancedFilter(
                aggregation = 'SUM',
                metric = instana_client.models.entity_metric.EntityMetric(
                    name = '', 
                    scope = instana_client.models.entity_metric_scope.EntityMetricScope(
                        tag_filter_expression = instana_client.models.tag_filter_expression_element.TagFilterExpressionElement(
                            type = '', ), 
                        type = '', ), ),
                operator = '>',
                threshold = 1.337
            )
        else:
            return AdvancedFilter(
                aggregation = 'SUM',
                metric = instana_client.models.entity_metric.EntityMetric(
                    name = '', 
                    scope = instana_client.models.entity_metric_scope.EntityMetricScope(
                        tag_filter_expression = instana_client.models.tag_filter_expression_element.TagFilterExpressionElement(
                            type = '', ), 
                        type = '', ), ),
                operator = '>',
                threshold = 1.337,
        )
        """

    def testAdvancedFilter(self):
        """Test AdvancedFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
