# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.api.fleet_management_api import FleetManagementApi


class TestFleetManagementApi(unittest.TestCase):
    """FleetManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FleetManagementApi()

    def tearDown(self) -> None:
        pass

    def test_create_fleet_config_assignment(self) -> None:
        """Test case for create_fleet_config_assignment

        Create a configuration assignment
        """
        pass

    def test_create_fleet_configuration(self) -> None:
        """Test case for create_fleet_configuration

        Creates a fleet configuration
        """
        pass

    def test_delete_custom_collector_base(self) -> None:
        """Test case for delete_custom_collector_base

        Delete a custom collector base configuration
        """
        pass

    def test_delete_fleet_config_assignment(self) -> None:
        """Test case for delete_fleet_config_assignment

        Delete a fleet configuration assignment
        """
        pass

    def test_get_custom_collector_base(self) -> None:
        """Test case for get_custom_collector_base

        Get fleet configuration details
        """
        pass

    def test_get_fleet_config_assignment(self) -> None:
        """Test case for get_fleet_config_assignment

        Get a fleet configuration assignment
        """
        pass

    def test_list_custom_collector_base(self) -> None:
        """Test case for list_custom_collector_base

        List fleet configurations
        """
        pass

    def test_list_fleet_config_assignments(self) -> None:
        """Test case for list_fleet_config_assignments

        List fleet configuration assignments
        """
        pass

    def test_update_custom_collector_base(self) -> None:
        """Test case for update_custom_collector_base

        Update a custom collector base configuration
        """
        pass

    def test_update_fleet_config_assignment(self) -> None:
        """Test case for update_fleet_config_assignment

        Update a fleet configuration assignment
        """
        pass


if __name__ == '__main__':
    unittest.main()
