# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.logs_api_response import LogsApiResponse

class TestLogsApiResponse(unittest.TestCase):
    """LogsApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LogsApiResponse:
        """Test LogsApiResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LogsApiResponse`
        """
        model = LogsApiResponse()
        if include_optional:
            return LogsApiResponse(
                adjusted_time_frame = '',
                can_load_more = True,
                items = [
                    instana_client.models.api_log_item.ApiLogItem(
                        aws/ecs/container_id = '', 
                        aws/ecs/container_name = '', 
                        containerd/container_id = '', 
                        crio/container_id = '', 
                        docker/container_id = '', 
                        docker/container_name = '', 
                        garden/container_id = '', 
                        kubernetes/cluster/name = '', 
                        kubernetes/container/name = '', 
                        kubernetes/deployment/name = '', 
                        kubernetes/namespace/name = '', 
                        kubernetes/node/name = '', 
                        kubernetes/pod/name = '', 
                        log/applications = [
                            ''
                            ], 
                        log/custom = [
                            instana_client.models.api_log_tag.ApiLogTag(
                                key = '', 
                                name = '', 
                                value = instana_client.models.value.value(), )
                            ], 
                        log/exception/message = '', 
                        log/exception/stack_trace = '', 
                        log/exception/type = '', 
                        log/expiration/ts/seconds = '', 
                        log/file/path = '', 
                        log/host_id = '', 
                        log/host_name = '', 
                        log/level = '', 
                        log/message = '', 
                        log/process_id = '', 
                        log/service_id = '', 
                        log/service_name = '', 
                        log/stream_name = '', 
                        log/timestamp = 0, 
                        log/trace_id = '', )
                    ],
                total_hits = 56
            )
        else:
            return LogsApiResponse(
        )
        """

    def testLogsApiResponse(self):
        """Test LogsApiResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
