# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.apdex_config_with_rbac_tag import ApdexConfigWithRBACTag

class TestApdexConfigWithRBACTag(unittest.TestCase):
    """ApdexConfigWithRBACTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApdexConfigWithRBACTag:
        """Test ApdexConfigWithRBACTag
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApdexConfigWithRBACTag`
        """
        model = ApdexConfigWithRBACTag()
        if include_optional:
            return ApdexConfigWithRBACTag(
                apdex_entity = instana_client.models.apdex_entity.ApdexEntity(
                    apdex_type = '', 
                    entity_id = '0', 
                    tag_filter_expression = instana_client.models.tag_filter_expression_element.TagFilterExpressionElement(
                        type = '', ), 
                    threshold = 1, ),
                apdex_name = '',
                created_at = 56,
                id = '',
                last_updated = 56,
                rbac_tags = [
                    instana_client.models.api_tag.ApiTag(
                        display_name = '', 
                        id = '', )
                    ],
                tags = [
                    ''
                    ]
            )
        else:
            return ApdexConfigWithRBACTag(
                apdex_entity = instana_client.models.apdex_entity.ApdexEntity(
                    apdex_type = '', 
                    entity_id = '0', 
                    tag_filter_expression = instana_client.models.tag_filter_expression_element.TagFilterExpressionElement(
                        type = '', ), 
                    threshold = 1, ),
                apdex_name = '',
                id = '',
        )
        """

    def testApdexConfigWithRBACTag(self):
        """Test ApdexConfigWithRBACTag"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
