# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.320.1414
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.api.slo_catalog_for_mobile_app_api import SLOCatalogForMobileAppApi


class TestSLOCatalogForMobileAppApi(unittest.TestCase):
    """SLOCatalogForMobileAppApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SLOCatalogForMobileAppApi()

    def tearDown(self) -> None:
        pass

    def test_get_mobile_app_sli_metric_catalog(self) -> None:
        """Test case for get_mobile_app_sli_metric_catalog

        Mobile app SLI metric catalog
        """
        pass

    def test_get_mobile_app_slo_tag_catalog(self) -> None:
        """Test case for get_mobile_app_slo_tag_catalog

        Get mobile app monitoring tag catalog for Mobile App SLOs
        """
        pass


if __name__ == '__main__':
    unittest.main()
