# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.315.1425
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.website_alert_config_with_rbac_tag import WebsiteAlertConfigWithRBACTag

class TestWebsiteAlertConfigWithRBACTag(unittest.TestCase):
    """WebsiteAlertConfigWithRBACTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebsiteAlertConfigWithRBACTag:
        """Test WebsiteAlertConfigWithRBACTag
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebsiteAlertConfigWithRBACTag`
        """
        model = WebsiteAlertConfigWithRBACTag()
        if include_optional:
            return WebsiteAlertConfigWithRBACTag(
                alert_channel_ids = [
                    '0'
                    ],
                alert_channels = {
                    'key' : [
                        ''
                        ]
                    },
                created = 1,
                custom_payload_fields = [
                    instana_client.models.custom_payload_field.CustomPayloadField(
                        key = '0', 
                        type = '', )
                    ],
                description = '',
                enabled = True,
                grace_period = 56,
                granularity = 60000,
                id = '',
                initial_created = 1,
                name = '',
                rbac_tags = [
                    instana_client.models.api_tag.ApiTag(
                        display_name = '', 
                        id = '', )
                    ],
                read_only = True,
                rule = instana_client.models.website_alert_rule.WebsiteAlertRule(
                    aggregation = 'SUM', 
                    alert_type = '', 
                    metric_name = '0', ),
                rules = [
                    instana_client.models.rule_with_threshold_website_alert_rule.RuleWithThresholdWebsiteAlertRule(
                        rule = instana_client.models.website_alert_rule.WebsiteAlertRule(
                            aggregation = 'SUM', 
                            alert_type = '', 
                            metric_name = '0', ), 
                        threshold_operator = '>', 
                        thresholds = {
                            'key' : instana_client.models.threshold_config_rule.ThresholdConfigRule(
                                type = '', )
                            }, )
                    ],
                severity = 5,
                tag_filter_expression = instana_client.models.tag_filter_expression_element.TagFilterExpressionElement(
                    type = '', ),
                tag_filters = [
                    instana_client.models.tag_filter.TagFilter()
                    ],
                threshold = instana_client.models.threshold.Threshold(
                    operator = '>', 
                    type = '', ),
                time_threshold = instana_client.models.website_time_threshold.WebsiteTimeThreshold(
                    time_window = 56, 
                    type = '', ),
                triggering = True,
                website_id = ''
            )
        else:
            return WebsiteAlertConfigWithRBACTag(
                custom_payload_fields = [
                    instana_client.models.custom_payload_field.CustomPayloadField(
                        key = '0', 
                        type = '', )
                    ],
                description = '',
                granularity = 60000,
                id = '',
                name = '',
                tag_filter_expression = instana_client.models.tag_filter_expression_element.TagFilterExpressionElement(
                    type = '', ),
                time_threshold = instana_client.models.website_time_threshold.WebsiteTimeThreshold(
                    time_window = 56, 
                    type = '', ),
                website_id = '',
        )
        """

    def testWebsiteAlertConfigWithRBACTag(self):
        """Test WebsiteAlertConfigWithRBACTag"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
