# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.319.1109
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.icmp_configuration_update import ICMPConfigurationUpdate

class TestICMPConfigurationUpdate(unittest.TestCase):
    """ICMPConfigurationUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ICMPConfigurationUpdate:
        """Test ICMPConfigurationUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ICMPConfigurationUpdate`
        """
        model = ICMPConfigurationUpdate()
        if include_optional:
            return ICMPConfigurationUpdate(
                packet_count = 56,
                packet_interval = '',
                packet_size = 56,
                packet_timeout = '',
                target_host = '',
                use_dns = True,
                use_ipv6 = True,
                validation_rules = instana_client.models.synthetic_resource_update_list_icmp_validation_list_icmp_validation.SyntheticResourceUpdateListICMPValidationListICMPValidation(
                    add = [
                        instana_client.models.icmp_validation.ICMPValidation(
                            key = '', 
                            operator = 'CONTAINS', 
                            value = 56, )
                        ], 
                    remove = [
                        instana_client.models.icmp_validation.ICMPValidation(
                            key = '', 
                            operator = 'CONTAINS', 
                            value = 56, )
                        ], )
            )
        else:
            return ICMPConfigurationUpdate(
        )
        """

    def testICMPConfigurationUpdate(self):
        """Test ICMPConfigurationUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
