# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.319.1109
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.ip_filtering import IPFiltering

class TestIPFiltering(unittest.TestCase):
    """IPFiltering unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IPFiltering:
        """Test IPFiltering
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IPFiltering`
        """
        model = IPFiltering()
        if include_optional:
            return IPFiltering(
                active = True,
                deny_all = True,
                enabled = True,
                last_changed_at = 56,
                last_verified_at = 56,
                rules = [
                    instana_client.models.ip_filtering_rule_dto.IPFilteringRuleDto(
                        block = True, 
                        target = '', )
                    ],
                support_access_enabled = True
            )
        else:
            return IPFiltering(
                rules = [
                    instana_client.models.ip_filtering_rule_dto.IPFilteringRuleDto(
                        block = True, 
                        target = '', )
                    ],
        )
        """

    def testIPFiltering(self):
        """Test IPFiltering"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
