# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.320.1414
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.apdex_alert_rule import ApdexAlertRule

class TestApdexAlertRule(unittest.TestCase):
    """ApdexAlertRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApdexAlertRule:
        """Test ApdexAlertRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApdexAlertRule`
        """
        model = ApdexAlertRule()
        if include_optional:
            return ApdexAlertRule(
                metric = 'SCORE'
            )
        else:
            return ApdexAlertRule(
                metric = 'SCORE',
        )
        """

    def testApdexAlertRule(self):
        """Test ApdexAlertRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
