# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.315.1425
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.session_replay_timestamps import SessionReplayTimestamps

class TestSessionReplayTimestamps(unittest.TestCase):
    """SessionReplayTimestamps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionReplayTimestamps:
        """Test SessionReplayTimestamps
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionReplayTimestamps`
        """
        model = SessionReplayTimestamps()
        if include_optional:
            return SessionReplayTimestamps(
                first_image_timestamp = 1234567890,
                last_image_timestamp = 1234567990
            )
        else:
            return SessionReplayTimestamps(
        )
        """

    def testSessionReplayTimestamps(self):
        """Test SessionReplayTimestamps"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
