# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.315.1425
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.llm_model_price_metadata import LlmModelPriceMetadata

class TestLlmModelPriceMetadata(unittest.TestCase):
    """LlmModelPriceMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LlmModelPriceMetadata:
        """Test LlmModelPriceMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LlmModelPriceMetadata`
        """
        model = LlmModelPriceMetadata()
        if include_optional:
            return LlmModelPriceMetadata(
                currency_code = '0'
            )
        else:
            return LlmModelPriceMetadata(
                currency_code = '0',
        )
        """

    def testLlmModelPriceMetadata(self):
        """Test LlmModelPriceMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
