# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.gateway_status_response import GatewayStatusResponse

class TestGatewayStatusResponse(unittest.TestCase):
    """GatewayStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GatewayStatusResponse:
        """Test GatewayStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GatewayStatusResponse`
        """
        model = GatewayStatusResponse()
        if include_optional:
            return GatewayStatusResponse(
                enabled = True,
                gateway_id = '',
                gateway_name = '',
                message = '',
                model_name = ''
            )
        else:
            return GatewayStatusResponse(
        )
        """

    def testGatewayStatusResponse(self):
        """Test GatewayStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
