# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.315.1425
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.synthetic_alert_config_with_rbac_tag import SyntheticAlertConfigWithRBACTag

class TestSyntheticAlertConfigWithRBACTag(unittest.TestCase):
    """SyntheticAlertConfigWithRBACTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyntheticAlertConfigWithRBACTag:
        """Test SyntheticAlertConfigWithRBACTag
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyntheticAlertConfigWithRBACTag`
        """
        model = SyntheticAlertConfigWithRBACTag()
        if include_optional:
            return SyntheticAlertConfigWithRBACTag(
                alert_channel_ids = [
                    '0'
                    ],
                created = 1,
                custom_payload_fields = [
                    instana_client.models.custom_payload_field.CustomPayloadField(
                        key = '0', 
                        type = '', )
                    ],
                description = '',
                enabled = True,
                grace_period = 56,
                id = '',
                initial_created = 1,
                name = '',
                rbac_tags = [
                    instana_client.models.api_tag.ApiTag(
                        display_name = '', 
                        id = '', )
                    ],
                read_only = True,
                rule = instana_client.models.synthetic_alert_rule.SyntheticAlertRule(
                    aggregation = 'SUM', 
                    alert_type = '', 
                    metric_name = '0', ),
                severity = 5,
                synthetic_test_ids = [
                    ''
                    ],
                tag_filter_expression = instana_client.models.tag_filter_expression_element.TagFilterExpressionElement(
                    type = '', ),
                time_threshold = instana_client.models.synthetic_time_threshold.SyntheticTimeThreshold(
                    type = '', 
                    violations_count = 1, )
            )
        else:
            return SyntheticAlertConfigWithRBACTag(
                alert_channel_ids = [
                    '0'
                    ],
                custom_payload_fields = [
                    instana_client.models.custom_payload_field.CustomPayloadField(
                        key = '0', 
                        type = '', )
                    ],
                description = '',
                id = '',
                name = '',
                rule = instana_client.models.synthetic_alert_rule.SyntheticAlertRule(
                    aggregation = 'SUM', 
                    alert_type = '', 
                    metric_name = '0', ),
                synthetic_test_ids = [
                    ''
                    ],
                tag_filter_expression = instana_client.models.tag_filter_expression_element.TagFilterExpressionElement(
                    type = '', ),
                time_threshold = instana_client.models.synthetic_time_threshold.SyntheticTimeThreshold(
                    type = '', 
                    violations_count = 1, ),
        )
        """

    def testSyntheticAlertConfigWithRBACTag(self):
        """Test SyntheticAlertConfigWithRBACTag"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
