# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.315.1425
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.llm_model_price import LlmModelPrice

class TestLlmModelPrice(unittest.TestCase):
    """LlmModelPrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LlmModelPrice:
        """Test LlmModelPrice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LlmModelPrice`
        """
        model = LlmModelPrice()
        if include_optional:
            return LlmModelPrice(
                default_input_cost = 1.337,
                default_output_cost = 1.337,
                has_default_price = True,
                input_cost = 1.337,
                is_user_defined = True,
                model_name = '',
                output_cost = 1.337,
                platform = '',
                provider = ''
            )
        else:
            return LlmModelPrice(
                input_cost = 1.337,
                output_cost = 1.337,
        )
        """

    def testLlmModelPrice(self):
        """Test LlmModelPrice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
