# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.319.1109
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.api.ip_filtering_api import IPFilteringApi


class TestIPFilteringApi(unittest.TestCase):
    """IPFilteringApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IPFilteringApi()

    def tearDown(self) -> None:
        pass

    def test_delete_ip_filtering(self) -> None:
        """Test case for delete_ip_filtering

        Delete current ip-filtering
        """
        pass

    def test_disable_ip_filtering(self) -> None:
        """Test case for disable_ip_filtering

        Disable the current ip-filtering
        """
        pass

    def test_get_ip_filtering(self) -> None:
        """Test case for get_ip_filtering

        Get current ip-filtering
        """
        pass

    def test_upsert_ip_filtering(self) -> None:
        """Test case for upsert_ip_filtering

        Upsert ip-filtering
        """
        pass

    def test_verify_ip_filtering(self) -> None:
        """Test case for verify_ip_filtering

        Verify current ip-filtering
        """
        pass


if __name__ == '__main__':
    unittest.main()
