# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.fleet_configuration_response import FleetConfigurationResponse

class TestFleetConfigurationResponse(unittest.TestCase):
    """FleetConfigurationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FleetConfigurationResponse:
        """Test FleetConfigurationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FleetConfigurationResponse`
        """
        model = FleetConfigurationResponse()
        if include_optional:
            return FleetConfigurationResponse(
                configuration = instana_client.models.fleet_configuration.FleetConfiguration(
                    configuration = instana_client.models.configuration.configuration(), 
                    configuration_id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '0', 
                    type = '0', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    version = '', ),
                configuration_version = '',
                id = '0',
                message = '0',
                status = '0'
            )
        else:
            return FleetConfigurationResponse(
                id = '0',
                message = '0',
                status = '0',
        )
        """

    def testFleetConfigurationResponse(self):
        """Test FleetConfigurationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
