# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.315.1425
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.ns1_integration import NS1Integration

class TestNS1Integration(unittest.TestCase):
    """NS1Integration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NS1Integration:
        """Test NS1Integration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NS1Integration`
        """
        model = NS1Integration()
        if include_optional:
            return NS1Integration(
                headers = [
                    '0'
                    ],
                webhook_urls = [
                    '0'
                    ]
            )
        else:
            return NS1Integration(
                webhook_urls = [
                    '0'
                    ],
        )
        """

    def testNS1Integration(self):
        """Test NS1Integration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
