# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.316.2780
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.apdex_level import ApdexLevel

class TestApdexLevel(unittest.TestCase):
    """ApdexLevel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApdexLevel:
        """Test ApdexLevel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApdexLevel`
        """
        model = ApdexLevel()
        if include_optional:
            return ApdexLevel(
                id = 0,
                lower = 0.94,
                name = 'Excellent',
                upper = 1.0
            )
        else:
            return ApdexLevel(
        )
        """

    def testApdexLevel(self):
        """Test ApdexLevel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
