# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.315.1425
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.api.llm_price_configuration_api import LLMPriceConfigurationApi


class TestLLMPriceConfigurationApi(unittest.TestCase):
    """LLMPriceConfigurationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LLMPriceConfigurationApi()

    def tearDown(self) -> None:
        pass

    def test_delete_llm_model_price(self) -> None:
        """Test case for delete_llm_model_price

        Delete LLM model price
        """
        pass

    def test_delete_llm_model_price_without_provider(self) -> None:
        """Test case for delete_llm_model_price_without_provider

        Delete LLM model price without provider
        """
        pass

    def test_get_all_llm_model_prices(self) -> None:
        """Test case for get_all_llm_model_prices

        Get all LLM model prices
        """
        pass

    def test_get_llm_model_currency(self) -> None:
        """Test case for get_llm_model_currency

        Get currency for LLM model prices
        """
        pass

    def test_get_llm_model_price(self) -> None:
        """Test case for get_llm_model_price

        Get LLM model price
        """
        pass

    def test_get_llm_model_price_without_provider(self) -> None:
        """Test case for get_llm_model_price_without_provider

        Get LLM model price without provider
        """
        pass

    def test_set_llm_model_currency(self) -> None:
        """Test case for set_llm_model_currency

        Set currency for LLM model prices
        """
        pass

    def test_upsert_llm_model_price(self) -> None:
        """Test case for upsert_llm_model_price

        Upsert LLM model price
        """
        pass

    def test_upsert_llm_model_price_without_provider(self) -> None:
        """Test case for upsert_llm_model_price_without_provider

        Upsert LLM model price without provider
        """
        pass


if __name__ == '__main__':
    unittest.main()
