# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.api.mobile_app_session_replay_api import MobileAppSessionReplayApi


class TestMobileAppSessionReplayApi(unittest.TestCase):
    """MobileAppSessionReplayApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MobileAppSessionReplayApi()

    def tearDown(self) -> None:
        pass

    def test_get_action_beacons(self) -> None:
        """Test case for get_action_beacons

        Get action beacons for a session
        """
        pass

    def test_get_session_replay_metadata(self) -> None:
        """Test case for get_session_replay_metadata

        Get session replay metadata
        """
        pass

    def test_get_session_replay_timestamps(self) -> None:
        """Test case for get_session_replay_timestamps

        Get session replay timestamps
        """
        pass


if __name__ == '__main__':
    unittest.main()
