# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.316.2780
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.cursor_pagination_with_ui_cursor_infra_explore_cursor import CursorPaginationWithUiCursorInfraExploreCursor

class TestCursorPaginationWithUiCursorInfraExploreCursor(unittest.TestCase):
    """CursorPaginationWithUiCursorInfraExploreCursor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CursorPaginationWithUiCursorInfraExploreCursor:
        """Test CursorPaginationWithUiCursorInfraExploreCursor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CursorPaginationWithUiCursorInfraExploreCursor`
        """
        model = CursorPaginationWithUiCursorInfraExploreCursor()
        if include_optional:
            return CursorPaginationWithUiCursorInfraExploreCursor(
                ingestion_time = 56,
                offset = 56,
                retrieval_size = 1
            )
        else:
            return CursorPaginationWithUiCursorInfraExploreCursor(
        )
        """

    def testCursorPaginationWithUiCursorInfraExploreCursor(self):
        """Test CursorPaginationWithUiCursorInfraExploreCursor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
