# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.rbac_restrictions import RbacRestrictions

class TestRbacRestrictions(unittest.TestCase):
    """RbacRestrictions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RbacRestrictions:
        """Test RbacRestrictions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RbacRestrictions`
        """
        model = RbacRestrictions()
        if include_optional:
            return RbacRestrictions(
                action_filters = [
                    ''
                    ],
                alerting_channels = [
                    ''
                    ],
                apdex_ids = [
                    ''
                    ],
                applications = [
                    ''
                    ],
                business_perspectives = [
                    ''
                    ],
                infra_dfq_filter = [
                    ''
                    ],
                kubernetes_clusters = [
                    ''
                    ],
                kubernetes_namespaces = [
                    ''
                    ],
                log_filters = [
                    ''
                    ],
                logging_perspectives = [
                    ''
                    ],
                mobile_apps = [
                    ''
                    ],
                service_levels = [
                    ''
                    ],
                synthetic_credentials = [
                    ''
                    ],
                synthetic_tests = [
                    ''
                    ],
                websites = [
                    ''
                    ]
            )
        else:
            return RbacRestrictions(
        )
        """

    def testRbacRestrictions(self):
        """Test RbacRestrictions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
