# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.fleet_configuration_assignment import FleetConfigurationAssignment

class TestFleetConfigurationAssignment(unittest.TestCase):
    """FleetConfigurationAssignment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FleetConfigurationAssignment:
        """Test FleetConfigurationAssignment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FleetConfigurationAssignment`
        """
        model = FleetConfigurationAssignment()
        if include_optional:
            return FleetConfigurationAssignment(
                agent_host = '0',
                agent_host_id = '0',
                agent_name = '',
                agent_type = '0',
                assignment_id = '',
                configuration_id = '0',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return FleetConfigurationAssignment(
                agent_host = '0',
                agent_host_id = '0',
                agent_type = '0',
                configuration_id = '0',
        )
        """

    def testFleetConfigurationAssignment(self):
        """Test FleetConfigurationAssignment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
