# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.315.1425
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.custom_tag import CustomTag

class TestCustomTag(unittest.TestCase):
    """CustomTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomTag:
        """Test CustomTag
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomTag`
        """
        model = CustomTag()
        if include_optional:
            return CustomTag(
                aggregation = 'FIRST',
                category = '',
                description = '',
                label = '',
                name = '',
                section = 'ACE',
                source = '',
                type = ''
            )
        else:
            return CustomTag(
        )
        """

    def testCustomTag(self):
        """Test CustomTag"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
