# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.316.2780
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.action_beacon import ActionBeacon

class TestActionBeacon(unittest.TestCase):
    """ActionBeacon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActionBeacon:
        """Test ActionBeacon
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionBeacon`
        """
        model = ActionBeacon()
        if include_optional:
            return ActionBeacon(
                beacon_type = 'ued',
                bytes_ingested_metadata = 1024,
                event_type = 'st',
                frustration_signal = 'rt',
                keyboard_operation = '',
                mobile_app_id = 'KVJIyIPsTUGfvNORN_07uQ',
                orientation_change = 'l',
                scroll_direction = '',
                scroll_duration = '',
                session_id = '24c6c1d4-161f-4243-85eb-3d0f46edbcbf',
                session_replay_version = '0.0.1',
                timestamp = 1757339999715,
                view_component_class_name = 'MaterialButton',
                view_component_id = 'resetDirectory'
            )
        else:
            return ActionBeacon(
                beacon_type = 'ued',
                mobile_app_id = 'KVJIyIPsTUGfvNORN_07uQ',
                session_id = '24c6c1d4-161f-4243-85eb-3d0f46edbcbf',
                timestamp = 1757339999715,
        )
        """

    def testActionBeacon(self):
        """Test ActionBeacon"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
