# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.319.1109
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.metric_field import MetricField

class TestMetricField(unittest.TestCase):
    """MetricField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetricField:
        """Test MetricField
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetricField`
        """
        model = MetricField()
        if include_optional:
            return MetricField(
                aggregation = 'SUM',
                entity_type = '',
                metric_id = '',
                time_window = None,
                value = instana_client.models.metric_field_value.MetricFieldValue(
                    aggregation = 'SUM', 
                    entity_type = '', 
                    metric_id = '', 
                    time_window = instana_client.models.time_window.timeWindow(), )
            )
        else:
            return MetricField(
        )
        """

    def testMetricField(self):
        """Test MetricField"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
