# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.319.1109
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.ip_filtering_upsert import IPFilteringUpsert

class TestIPFilteringUpsert(unittest.TestCase):
    """IPFilteringUpsert unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IPFilteringUpsert:
        """Test IPFilteringUpsert
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IPFilteringUpsert`
        """
        model = IPFilteringUpsert()
        if include_optional:
            return IPFilteringUpsert(
                deny_all = True,
                enabled = True,
                rules = [
                    instana_client.models.ip_filtering_rule_dto.IPFilteringRuleDto(
                        block = True, 
                        target = '', )
                    ],
                support_access_enabled = True
            )
        else:
            return IPFilteringUpsert(
                deny_all = True,
                enabled = True,
                rules = [
                    instana_client.models.ip_filtering_rule_dto.IPFilteringRuleDto(
                        block = True, 
                        target = '', )
                    ],
                support_access_enabled = True,
        )
        """

    def testIPFilteringUpsert(self):
        """Test IPFilteringUpsert"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
