# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.323.989
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.trace_sampling_config import TraceSamplingConfig

class TestTraceSamplingConfig(unittest.TestCase):
    """TraceSamplingConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TraceSamplingConfig:
        """Test TraceSamplingConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TraceSamplingConfig`
        """
        model = TraceSamplingConfig()
        if include_optional:
            return TraceSamplingConfig(
                created_at = 56,
                enabled = True,
                evaluation_window_minutes = 1,
                retention_percentage = 0.01,
                sampling_frequency_hours = 0,
                sampling_rate = 0,
                sampling_type = '',
                tenant_unit_id = '',
                updated_at = 56,
                volume_strategy = ''
            )
        else:
            return TraceSamplingConfig(
                enabled = True,
                sampling_type = '',
                volume_strategy = '',
        )
        """

    def testTraceSamplingConfig(self):
        """Test TraceSamplingConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
