# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.316.2780
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from instana_client.models.slo_report import SloReport

from instana_client.api_client import ApiClient, RequestSerialized
from instana_client.api_response import ApiResponse
from instana_client.rest import RESTResponseType


class ServiceLevelsObjectiveSLOReportApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def entities_slo(
        self,
        slo_id: Annotated[StrictStr, Field(description="Service Levels Objective(SLO) Configuration ID")],
        window_size: Annotated[Optional[StrictInt], Field(description="Size of the time window in which the monitored entities must be fetched, specified in milliseconds. If not provided or set to 0, the default value of 3600000 milliseconds (1 hour) is used.")] = None,
        to: Annotated[Optional[StrictInt], Field(description="Ending point for the data retrieval, specified as a 13-digit Unix timestamp in milliseconds. If not provided or set to 0, the current system time will be used.")] = None,
        page_size: Annotated[Optional[StrictInt], Field(description="Size of the Page")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page Number")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[str]:
        """Get the entities monitored by a SLO (Service Level Objective) configuration


        :param slo_id: Service Levels Objective(SLO) Configuration ID (required)
        :type slo_id: str
        :param window_size: Size of the time window in which the monitored entities must be fetched, specified in milliseconds. If not provided or set to 0, the default value of 3600000 milliseconds (1 hour) is used.
        :type window_size: int
        :param to: Ending point for the data retrieval, specified as a 13-digit Unix timestamp in milliseconds. If not provided or set to 0, the current system time will be used.
        :type to: int
        :param page_size: Size of the Page
        :type page_size: int
        :param page: Page Number
        :type page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._entities_slo_serialize(
            slo_id=slo_id,
            window_size=window_size,
            to=to,
            page_size=page_size,
            page=page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '404': "List[str]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def entities_slo_with_http_info(
        self,
        slo_id: Annotated[StrictStr, Field(description="Service Levels Objective(SLO) Configuration ID")],
        window_size: Annotated[Optional[StrictInt], Field(description="Size of the time window in which the monitored entities must be fetched, specified in milliseconds. If not provided or set to 0, the default value of 3600000 milliseconds (1 hour) is used.")] = None,
        to: Annotated[Optional[StrictInt], Field(description="Ending point for the data retrieval, specified as a 13-digit Unix timestamp in milliseconds. If not provided or set to 0, the current system time will be used.")] = None,
        page_size: Annotated[Optional[StrictInt], Field(description="Size of the Page")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page Number")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[str]]:
        """Get the entities monitored by a SLO (Service Level Objective) configuration


        :param slo_id: Service Levels Objective(SLO) Configuration ID (required)
        :type slo_id: str
        :param window_size: Size of the time window in which the monitored entities must be fetched, specified in milliseconds. If not provided or set to 0, the default value of 3600000 milliseconds (1 hour) is used.
        :type window_size: int
        :param to: Ending point for the data retrieval, specified as a 13-digit Unix timestamp in milliseconds. If not provided or set to 0, the current system time will be used.
        :type to: int
        :param page_size: Size of the Page
        :type page_size: int
        :param page: Page Number
        :type page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._entities_slo_serialize(
            slo_id=slo_id,
            window_size=window_size,
            to=to,
            page_size=page_size,
            page=page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '404': "List[str]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def entities_slo_without_preload_content(
        self,
        slo_id: Annotated[StrictStr, Field(description="Service Levels Objective(SLO) Configuration ID")],
        window_size: Annotated[Optional[StrictInt], Field(description="Size of the time window in which the monitored entities must be fetched, specified in milliseconds. If not provided or set to 0, the default value of 3600000 milliseconds (1 hour) is used.")] = None,
        to: Annotated[Optional[StrictInt], Field(description="Ending point for the data retrieval, specified as a 13-digit Unix timestamp in milliseconds. If not provided or set to 0, the current system time will be used.")] = None,
        page_size: Annotated[Optional[StrictInt], Field(description="Size of the Page")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page Number")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get the entities monitored by a SLO (Service Level Objective) configuration


        :param slo_id: Service Levels Objective(SLO) Configuration ID (required)
        :type slo_id: str
        :param window_size: Size of the time window in which the monitored entities must be fetched, specified in milliseconds. If not provided or set to 0, the default value of 3600000 milliseconds (1 hour) is used.
        :type window_size: int
        :param to: Ending point for the data retrieval, specified as a 13-digit Unix timestamp in milliseconds. If not provided or set to 0, the current system time will be used.
        :type to: int
        :param page_size: Size of the Page
        :type page_size: int
        :param page: Page Number
        :type page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._entities_slo_serialize(
            slo_id=slo_id,
            window_size=window_size,
            to=to,
            page_size=page_size,
            page=page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '404': "List[str]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _entities_slo_serialize(
        self,
        slo_id,
        window_size,
        to,
        page_size,
        page,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if slo_id is not None:
            _path_params['sloId'] = slo_id
        # process the query parameters
        if window_size is not None:
            
            _query_params.append(('windowSize', window_size))
            
        if to is not None:
            
            _query_params.append(('to', to))
            
        if page_size is not None:
            
            _query_params.append(('pageSize', page_size))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/slo/entities/{sloId}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def explain_slo(
        self,
        slo_id: Annotated[StrictStr, Field(description="Service Levels Objective(SLO) Configuration ID")],
        var_from: Annotated[Optional[StrictStr], Field(description="Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        to: Annotated[Optional[StrictStr], Field(description="Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[str]:
        """Explain Service Levels objective with more details.


        :param slo_id: Service Levels Objective(SLO) Configuration ID (required)
        :type slo_id: str
        :param var_from: Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type var_from: str
        :param to: Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type to: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._explain_slo_serialize(
            slo_id=slo_id,
            var_from=var_from,
            to=to,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '404': "List[str]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def explain_slo_with_http_info(
        self,
        slo_id: Annotated[StrictStr, Field(description="Service Levels Objective(SLO) Configuration ID")],
        var_from: Annotated[Optional[StrictStr], Field(description="Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        to: Annotated[Optional[StrictStr], Field(description="Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[str]]:
        """Explain Service Levels objective with more details.


        :param slo_id: Service Levels Objective(SLO) Configuration ID (required)
        :type slo_id: str
        :param var_from: Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type var_from: str
        :param to: Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type to: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._explain_slo_serialize(
            slo_id=slo_id,
            var_from=var_from,
            to=to,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '404': "List[str]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def explain_slo_without_preload_content(
        self,
        slo_id: Annotated[StrictStr, Field(description="Service Levels Objective(SLO) Configuration ID")],
        var_from: Annotated[Optional[StrictStr], Field(description="Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        to: Annotated[Optional[StrictStr], Field(description="Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Explain Service Levels objective with more details.


        :param slo_id: Service Levels Objective(SLO) Configuration ID (required)
        :type slo_id: str
        :param var_from: Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type var_from: str
        :param to: Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type to: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._explain_slo_serialize(
            slo_id=slo_id,
            var_from=var_from,
            to=to,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '404': "List[str]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _explain_slo_serialize(
        self,
        slo_id,
        var_from,
        to,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if slo_id is not None:
            _path_params['sloId'] = slo_id
        # process the query parameters
        if var_from is not None:
            
            _query_params.append(('from', var_from))
            
        if to is not None:
            
            _query_params.append(('to', to))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/slo/explain/{sloId}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_slo(
        self,
        slo_id: Annotated[StrictStr, Field(description="SLO Configuration ID")],
        var_from: Annotated[Optional[StrictStr], Field(description="Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        to: Annotated[Optional[StrictStr], Field(description="Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        exclude_correction_id: Annotated[Optional[List[StrictStr]], Field(description="IDs of Correction Configurations to be Excluded from the result")] = None,
        include_correction_id: Annotated[Optional[List[StrictStr]], Field(description="IDs of Correction Configurations to be Included in the result")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[SloReport]:
        """Generate Service Levels report


        :param slo_id: SLO Configuration ID (required)
        :type slo_id: str
        :param var_from: Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type var_from: str
        :param to: Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type to: str
        :param exclude_correction_id: IDs of Correction Configurations to be Excluded from the result
        :type exclude_correction_id: List[str]
        :param include_correction_id: IDs of Correction Configurations to be Included in the result
        :type include_correction_id: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_slo_serialize(
            slo_id=slo_id,
            var_from=var_from,
            to=to,
            exclude_correction_id=exclude_correction_id,
            include_correction_id=include_correction_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SloReport]",
            '404': "List[str]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_slo_with_http_info(
        self,
        slo_id: Annotated[StrictStr, Field(description="SLO Configuration ID")],
        var_from: Annotated[Optional[StrictStr], Field(description="Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        to: Annotated[Optional[StrictStr], Field(description="Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        exclude_correction_id: Annotated[Optional[List[StrictStr]], Field(description="IDs of Correction Configurations to be Excluded from the result")] = None,
        include_correction_id: Annotated[Optional[List[StrictStr]], Field(description="IDs of Correction Configurations to be Included in the result")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[SloReport]]:
        """Generate Service Levels report


        :param slo_id: SLO Configuration ID (required)
        :type slo_id: str
        :param var_from: Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type var_from: str
        :param to: Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type to: str
        :param exclude_correction_id: IDs of Correction Configurations to be Excluded from the result
        :type exclude_correction_id: List[str]
        :param include_correction_id: IDs of Correction Configurations to be Included in the result
        :type include_correction_id: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_slo_serialize(
            slo_id=slo_id,
            var_from=var_from,
            to=to,
            exclude_correction_id=exclude_correction_id,
            include_correction_id=include_correction_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SloReport]",
            '404': "List[str]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_slo_without_preload_content(
        self,
        slo_id: Annotated[StrictStr, Field(description="SLO Configuration ID")],
        var_from: Annotated[Optional[StrictStr], Field(description="Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        to: Annotated[Optional[StrictStr], Field(description="Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        exclude_correction_id: Annotated[Optional[List[StrictStr]], Field(description="IDs of Correction Configurations to be Excluded from the result")] = None,
        include_correction_id: Annotated[Optional[List[StrictStr]], Field(description="IDs of Correction Configurations to be Included in the result")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Generate Service Levels report


        :param slo_id: SLO Configuration ID (required)
        :type slo_id: str
        :param var_from: Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type var_from: str
        :param to: Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type to: str
        :param exclude_correction_id: IDs of Correction Configurations to be Excluded from the result
        :type exclude_correction_id: List[str]
        :param include_correction_id: IDs of Correction Configurations to be Included in the result
        :type include_correction_id: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_slo_serialize(
            slo_id=slo_id,
            var_from=var_from,
            to=to,
            exclude_correction_id=exclude_correction_id,
            include_correction_id=include_correction_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[SloReport]",
            '404': "List[str]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_slo_serialize(
        self,
        slo_id,
        var_from,
        to,
        exclude_correction_id,
        include_correction_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'excludeCorrectionId': 'multi',
            'includeCorrectionId': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if slo_id is not None:
            _path_params['sloId'] = slo_id
        # process the query parameters
        if var_from is not None:
            
            _query_params.append(('from', var_from))
            
        if to is not None:
            
            _query_params.append(('to', to))
            
        if exclude_correction_id is not None:
            
            _query_params.append(('excludeCorrectionId', exclude_correction_id))
            
        if include_correction_id is not None:
            
            _query_params.append(('includeCorrectionId', include_correction_id))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/slo/report/{sloId}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def summarize_slo(
        self,
        slo_id: Annotated[StrictStr, Field(description="Service Levels Objective(SLO) Configuration ID")],
        var_from: Annotated[Optional[StrictStr], Field(description="Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        to: Annotated[Optional[StrictStr], Field(description="Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[str]:
        """Summarize Service Levels objective results.


        :param slo_id: Service Levels Objective(SLO) Configuration ID (required)
        :type slo_id: str
        :param var_from: Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type var_from: str
        :param to: Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type to: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._summarize_slo_serialize(
            slo_id=slo_id,
            var_from=var_from,
            to=to,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '404': "List[str]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def summarize_slo_with_http_info(
        self,
        slo_id: Annotated[StrictStr, Field(description="Service Levels Objective(SLO) Configuration ID")],
        var_from: Annotated[Optional[StrictStr], Field(description="Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        to: Annotated[Optional[StrictStr], Field(description="Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[str]]:
        """Summarize Service Levels objective results.


        :param slo_id: Service Levels Objective(SLO) Configuration ID (required)
        :type slo_id: str
        :param var_from: Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type var_from: str
        :param to: Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type to: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._summarize_slo_serialize(
            slo_id=slo_id,
            var_from=var_from,
            to=to,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '404': "List[str]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def summarize_slo_without_preload_content(
        self,
        slo_id: Annotated[StrictStr, Field(description="Service Levels Objective(SLO) Configuration ID")],
        var_from: Annotated[Optional[StrictStr], Field(description="Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        to: Annotated[Optional[StrictStr], Field(description="Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Summarize Service Levels objective results.


        :param slo_id: Service Levels Objective(SLO) Configuration ID (required)
        :type slo_id: str
        :param var_from: Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type var_from: str
        :param to: Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        :type to: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._summarize_slo_serialize(
            slo_id=slo_id,
            var_from=var_from,
            to=to,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '404': "List[str]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _summarize_slo_serialize(
        self,
        slo_id,
        var_from,
        to,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if slo_id is not None:
            _path_params['sloId'] = slo_id
        # process the query parameters
        if var_from is not None:
            
            _query_params.append(('from', var_from))
            
        if to is not None:
            
            _query_params.append(('to', to))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/slo/summarize/{sloId}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


